#!/bin/bash
set -e

MYSQL_RAM_SIZE=${MYSQL_RAM_SIZE:-"2048"}

echo "Mounting MySQL with ${MYSQL_RAM_SIZE}MB of RAM."
mkdir -p /var/lib/mysql
mount -t tmpfs -o size="${MYSQL_RAM_SIZE}m" tmpfs /var/lib/mysql

chown -R mysql:mysql /var/lib/mysql
mysql_install_db --user mysql > /dev/null

tfile=`mktemp`
if [[ ! -f "$tfile" ]]; then
    return 1
fi

cat << EOF > $tfile
USE mysql;
FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
UPDATE user SET password=PASSWORD("") WHERE user='root';
EOF

/usr/sbin/mysqld --bootstrap --verbose=0 < $tfile
rm -f $tfile

exec /usr/sbin/mysqld
